name: Deploy and Upgrade Odoo

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy and Upgrade
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            # 1. تحديث الكود من GitHub
            cd /opt/odoo_docker/Jasmine_custom
            git reset --hard origin/main
            git pull origin main
            
            # 2. الانتقال للمسار الرئيسي
            cd /opt/odoo_docker
            
            # 3. إعادة التشغيل
            if command -v docker compose &> /dev/null; then
                docker compose restart web_ent
            else
                /usr/local/bin/docker-compose restart web_ent
            fi
            
            # 4. تحديث الموديلات (Upgrade)
            # ننتظر 5 ثوانٍ لضمان استقرار حاوية أودو قبل البدء بالتحديث
            sleep 5
            docker compose exec -T web_ent python3 /opt/odoo/odoo-core/odoo-bin -c /etc/odoo/odoo.conf -d erp-jasmine -u all --stop-after-init